name: generate pacman contribution graphs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: "pacman,breakout"

      - name: Debug
        run: |
          echo "Current directory:"
          pwd
          echo ""
          echo "All files:"
          find . -type f
          echo ""
          echo "All directories:"
          find . -type d

      - name: Push SVGs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-pacman
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}